# Generated by Django 3.0.3 on 2020-02-20 18:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tools', '0002_auto_20200220_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='available',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default='True'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tool',
            name='owner',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tool',
            name='posted',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='tool',
            name='tool',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='tool',
            name='type',
            field=models.CharField(choices=[('AUTO', 'Auto'), ('PLUMBING', 'Plumbing'), ('BIKE', 'Bike'), ('YARD', 'Yard'), ('WOODWORKING', 'Woodworking')], default='AUTO', max_length=30),
        ),
    ]
