# Generated by Django 3.0.3 on 2020-02-20 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_auto_20200220_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='type',
            field=models.CharField(choices=[('Automobile', 'Auto'), ('Plumbing', 'Plumbing'), ('Bike', 'Bike'), ('Yard', 'Yard'), ('Woodworking', 'Woodworking')], default='AUTO', max_length=30),
        ),
    ]
