# Generated by Django 3.0.3 on 2020-02-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0006_tool_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='available',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
    ]
