# Generated by Django 3.0.3 on 2020-02-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0007_auto_20200222_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='borrowed',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
    ]
